plugins {
    id 'com.gradleup.shadow' version "${shadow_version}"
    id 'net.neoforged.gradle.userdev' version "${neogradle_version}"
    id 'mod-update' version "${mod_update_version}"
    id 'com.matthewprenger.cursegradle' version "${cursegradle_version}"
    id 'com.modrinth.minotaur' version "${minotaur_version}"
}

apply from: "https://raw.githubusercontent.com/henkelmax/mod-gradle-scripts/${mod_gradle_script_version}/mod.gradle"

repositories {

}

dependencies {
    implementation "de.maxhenkel.voicechat:voicechat-api:${voicechat_api_version}"
    runtimeOnly "maven.modrinth:simple-voice-chat:neoforge-${voicechat_mod_version}"

    jarJar(implementation("maven.modrinth:admiral:${admiral_version}+neoforge"))
}

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
    }
    
    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }
    
    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }
}

processResources {
    filesMatching('META-INF/neoforge.mods.toml') {
        expand 'mod_version': mod_version,
                'minecraft_dependency': minecraft_dependency,
                'minecraft_version': minecraft_version,
                'neoforge_dependency': neoforge_dependency,
                'voicechat_api_version': voicechat_api_version
    }
}
